# -*- coding: UTF-8 -*-


class ProxyFilter(object):
    """
    ProxyFilter is used to seperate the representation of filter and the actually
    filter generated by data set
    """
    def __init__(self, name, operators, shown, type, options):
        self.name = name
        self.operators = operators
        self.shown = shown
        self.type = type
        self.options = options

    def __call__(self, value):
        raise NotImplementedError('unimplemented')

