name: 三国实力报告
description: 三国时期各个国家的情况分析
creator: 智冠 
create_time: 2013-07-02 07:30:00
filters:
  Group.name:
    operators: [eq, ne]
  User.impact:
    name: 影响力
    operators: [eq, ne]
  sum(User.impact):
    operators: [eq, ne]
order_bys:
  - 国家
  - User.group_id